'on':
    push:
      branches:
        - main
        - renovate/**
    pull_request:
        types:
        - opened
        - synchronize


permissions:
    contents: read

jobs:
    verify:
        uses: travi-test/.github/.github/workflows/reusable-test.yml@master